### ISSUE TITLE
Bug: Not Compatible with 2.10 (Glimmer 2) & Emberfire

### ISSUE THREAD

**Issue by maprules1000** [selvagsz/ember-carousel#11]
Trying to use this with 2.10 (Which includes Glimmer 2) and I get this error message:

`Assertion Failed: You modified isActive twice on <...carousel-item> in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See `[https://github.com/emberjs/ember.js/issues/13948](https://github.com/emberjs/ember.js/issues/13948)` for more details.`

It looks like this relied on a deprecated pattern of setting values while the component was still rendering and now, with Glimmer 2 in 2.10, that deprecated pattern has been wholly prevented which prevents ember-carousel from working.

**Comment by knownasilya** [comment]
Hum, this doesn't seem to always happen, since I have an app running 2.10 and this addon, see https://newtonma.mapgeo.io/properties/23017%200001?latlng=42.354271%2C-71.200375&selected=23017%200001&zoom=18 (property image section in the left panel)

Seems we can change how we calculate the `isActive` property, maybe using `didReceiveAttrs` and passing in the lastObject to the item component.

**Comment by maprules1000** [comment]
@knownasilya Huh, that's interesting. I'll investigate the issue some more and see if the error might stem from another add-on that interacts with it.

**Comment by maprules1000** [comment]
@knownasilya it looks like a problem when using this carousel with Firebase's emberfire addon. Unfortunately the error from firebase is just `firebase.js:313 FIREBASE WARNING: Exception was thrown by user callback. Error` with a stacktrace of a minified file @_@, and no details from the ember error. I'll have to dig into it to even log an issue with the Firebase team.

I'll explore your suggestion to see if that fixes the problem.

**Comment by knownasilya** [comment]
Really I feel like converting this to a contextual component, will help this issue. See https://github.com/selvagsz/ember-carousel/issues/1#issuecomment-260440182

**Comment by maprules1000** [comment]
@knownasilya That would help for sure, but I think you'd still run into errors since a bunch of things are getting set on init.

At first pass changing `init()` to `didInsertElement()` removes the error and gets everything working again, and it looks like it doesn't have any noticeable effect on the component. Would that be a good immediate fix for this? I can open up a PR.

**Comment by knownasilya** [comment]
Yes, that would be fine, as long as everything still works.
