### ISSUE TITLE
The installation process is corrupted in some way.

### ISSUE THREAD

**Issue by Romanior** [selvagsz/ember-carousel#14]
I tried to install with `ember install ember-carousel`, the installation works fine, but in the 
`/node_modules/ember-carousel/addon/templates/components/carousel-container.hbs`. There is only single line of`{{yeild}}` in the file. Obviously the component does not work.

<img width="890" alt="screen shot 2017-11-01 at 19 56 04" src="https://user-images.githubusercontent.com/490365/32286503-bc851a3a-bf3e-11e7-829a-19817a3252ff.png">

**Comment by knownasilya** [comment]
The installation is not corrupt,  the version in master had not yet been published. https://github.com/selvagsz/ember-carousel/blob/e6565bcffac67847ceb08e91f49e6b97cb84acb3/README.md is the documentation for the last published version.

**Comment by Romanior** [comment]
ok 👍
