### ISSUE TITLE
Example on `npmjs.org` is out of date

### ISSUE THREAD

**Issue by bendemboski** [selvagsz/ember-carousel#15]
I'm not sure if this is an issue with `npmjs.org` or some config problem with this project, but figured you'd want to know that the example on [npmjs.org](https://www.npmjs.com/package/ember-carousel) is from an older version of the README. It shows

```
{{#carousel-container transitionInterval=400}}
  {{#carousel-body}}
    {{#carousel-item}}
      Emberjs
    {{/carousel-item}}
    {{#carousel-item}}
      Reactjs
    {{/carousel-item}}
    {{#carousel-item}}
      Angularjs
    {{/carousel-item}}
  {{/carousel-body}}
 
  {{#carousel-arrow direction="left" tagName="button"}}
    Slide Left
  {{/carousel-arrow}}
  {{#carousel-arrow direction="right" tagName="button"}}
    Slide Right
  {{/carousel-arrow}}
{{/carousel-container}}
```

instead of the contextual syntax.

**Comment by knownasilya** [comment]
The code in master hasn't been released yet. Would love your help to use it in an app so we can say it's ready for a release.

**Comment by bendemboski** [comment]
Ah, I think some `yarn` funniness resulted in me running against the head of master instead of the latest release, so I thought it was released. I don't think the app is really going to be ready for a while yet, sorry.
